mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.SpringBootDemo.domain

spring:
  datasource:
    hikari: #数据库连接池配置信息
      connection-timeout: 60000
      minimum-idle: 2
      maximum-pool-size: 2
      idle-timeout: 6000
      max-lifetime: 6000
      connection-test-query: select 1
      validation-timeout: 10000

logging:
  root:
    level: INFO

#
management:
  security:
    enabled: false
