mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.SpringBootDemo.domain

#指定日志配置文件 - 根据不同环境加载不同日志配置文件
logging:
  config:
    classpath: logback-spring.xml

management:
  security:
    enabled: false